### ISSUE TITLE
0.3.1 doesn't build with GHC 9.0

### ISSUE THREAD

**Issue by felixonmars** [tweag/linear-base#441]
**Describe the bug**
0.3.1 doesn't build with GHC 9.0:

```
[ 4 of 89] Compiling Data.Tuple.Linear.Compat ( src-version-changes/ghc96/before/Data/Tuple/Linear/Compat.hs, dist/build/Data/Tuple/Linear/Compat.dyn_o )
DEBUG:root:haskell-linear-base:
src-version-changes/ghc96/before/Data/Tuple/Linear/Compat.hs:12:11: error:
    Not in scope: type constructor or class ‘Solo’
   |
12 | unSolo :: Solo a %p -> a
   |           ^^^^
DEBUG:root:haskell-linear-base:
src-version-changes/ghc96/before/Data/Tuple/Linear/Compat.hs:13:9: error:
    Not in scope: data constructor ‘Solo’
   |
13 | unSolo (Solo a) = a
   |         ^^^^
DEBUG:root:haskell-linear-base:
src-version-changes/ghc96/before/Data/Tuple/Linear/Compat.hs:16:19: error:
    Not in scope: type constructor or class ‘Solo’
   |
16 | mkSolo :: a %p -> Solo a
   |                   ^^^^
```

If this is expected, probably we should note it in the changelog and probably tighten bounds accordingly?

**Environment**
 - OS name + version:
 - Version of the code:

**Additional context**

**Comment by aspiwack** [comment]
I guess 0.3.0 doesn't compile with GHC 9.0 either? These functions are new, but, the `Solo` type was already mentioned. I would be grateful if you could test it.

At any rate, this is unsurprising: the support for 9.0 was accidental at this point. The library lives at the edge by design. It is likely that 0.4, whenever it's out even support 9.2 (though 9.4 support stays at least as long as 9.6 isn't stable on Stackage).

I can push revisions to Hackage, and add a corresponding bound in the Cabal file.
