### ISSUE TITLE
linear-base-0.1.0 build failure with GHC 9.8

### ISSUE THREAD

**Issue by andreasabel** [tweag/linear-base#464]
The released `linear-base-0.10` fails to build with GHC 9.8:
```
src/Data/Array/Polarized/Pull/Internal.hs:70:19: error: [GHC-39999]
    • No instance for ‘Prelude.Eq t’ arising from the literal ‘0’
      Possible fix:
        add (Prelude.Eq t) to the context of
          the inferred type of
            go :: (w1 %1 -> w2 %1 -> w2) -> w2 %1 -> (t -> w1) -> t -> w2
    • In the pattern: 0
      In an equation for ‘go’: go _ z' _ 0 = z'
      In an equation for ‘Data.Array.Polarized.Pull.Internal.foldr’:
          Data.Array.Polarized.Pull.Internal.foldr f z (Array g n)
            = go f z g n
            where
                go :: (_ %1 -> _ %1 -> _) -> _ %1 -> _ -> _ -> _
                go _ z' _ 0 = z'
                go f' z' g' k = go f' (f' (g' (k - 1)) z') g' (k - 1)
   |
70 |         go _ z' _ 0 = z'
   |                   ^

src/Data/Array/Polarized/Pull/Internal.hs:71:41: error: [GHC-39999]
    • No instance for ‘AdditiveGroup t’ arising from a use of ‘-’
      Possible fix:
        add (AdditiveGroup t) to the context of
          the inferred type of
            go :: (w1 %1 -> w2 %1 -> w2) -> w2 %1 -> (t -> w1) -> t -> w2
    • In the first argument of ‘g'’, namely ‘(k - 1)’
      In the first argument of ‘f'’, namely ‘(g' (k - 1))’
      In the second argument of ‘go’, namely ‘(f' (g' (k - 1)) z')’
   |
71 |         go f' z' g' k = go f' (f' (g' (k-1)) z') g' (k-1)
   |                                         ^
```
It should be revised on hackage so that it is not picked up in situations where it cannot build.  Currently it lacks most upper bounds of its dependencies, I do not know which dependency is responsible for the failure here.

**Comment by andreasabel** [comment]
Since no published version builds with GHC 9.8 (the other versions restrict `template-haskell`), I suppose `linear-base-0.1.0` was not intended to build with future GHCs, so I restricted `base < 4.19`, see revision 1: https://hackage.haskell.org/package/linear-base-0.1.0/revisions/

**Comment by monoidal** [comment]
Yes, there's a backwards incompatible typechecker change in 9.8. I've addressed that in #457 but it needs a new release of `linear-base`. cc @aspiwack 

The `base < 4.19` restriction should also apply to other versions right now on hackage: 0.2.0, 0.3.0, 0.3.1.

**Comment by andreasabel** [comment]
> The `base < 4.19` restriction should also apply to other versions right now on hackage: 0.2.0, 0.3.0, 0.3.1.

I didn't do this because they are blocked by a `template-haskell` constraint already:
>  trying: linear-base-0.3.1 (user goal)
> [__1] trying: linear-generics-0.2.2 (dependency of linear-base)
> [__2] next goal: template-haskell (dependency of linear-generics)
> [__2] rejecting: template-haskell-2.21.0.0/installed-be6e (conflict: linear-generics => template-haskell>=2.16 && <2.21)

But maybe it would be cleaner.

**Comment by aspiwack** [comment]
Thanks @andreasabel and @monoidal ! I thought I had released #457 . My bad. I'll make a release on Friday (tomorrow).

**Comment by aspiwack** [comment]
I've just released v0.4.0 https://hackage.haskell.org/package/linear-base-0.4.0

(the documentation should be built by the bot pretty soon)

Thanks again both. I still need to add GHC 9.8 to the CI. I'll wait a couple of weeks for that.

**Comment by andreasabel** [comment]
Build is still blocked on the dependency:
- [ ] https://github.com/linear-generics/linear-generics/issues/25
