### ISSUE TITLE
linear-base 0.8.0 does not build with GHC 9.2

### ISSUE THREAD

**Issue by Lysxia** [tweag/linear-base#510]
- linear-base 0.8.0
- GHC 9.2.8

Error message:

```
src/Control/Functor/Linear/Internal/Reader.hs:38:18: error:
    Module ‘GHC.Exts’ does not export ‘Multiplicity(..)’
   |
38 | import GHC.Exts (Multiplicity (..))
   |                  ^^^^^^^^^^^^^^^^^
```

Fix: update the lower bound on base on Hackage.

**Comment by aspiwack** [comment]
Ah, yes, thanks. I'd been warned by #509 , but got distracted and forgot to follow through.

I've updated the bound on Hackage, hopefully it solves the particular problem of the bound lying.

And I'll be adding 9.4 in the CI with #511 and upload a new version which hopefully works with 9.2.

**Comment by aspiwack** [comment]
Published https://hackage.haskell.org/package/linear-base-0.8.1

Now the solver should avoid 0.8.0 but select 0.8.1 with GHC 9.2.8 (on the latest index). Hopefully no more surprises.

Thanks again for reporting.

**Comment by Lysxia** [comment]
I tried rebuilding stuff in the meantime before 0.8.1 and it appears that 0.7.0 also doesn't build with GHC 9.2 :)

**Comment by aspiwack** [comment]
Grmbl. This should be fixed too. Maybe this dates back a few versions like this… Probably even.

Thanks for testing all that.
