### ISSUE TITLE
Fails to build with GHC 9.6 alpha2

### ISSUE THREAD

**Issue by Lysxia** [tweag/linear-base#437]
**Describe the bug**

Building linear-base 0.3.0 with GHC 9.6 fails with a type error. It seems that the `Solo` tuple is not handled correctly.

**To Reproduce**

```
cabal install linear-base
```

```
src/Data/Monoid/Linear/Internal/Semigroup.hs:168:3: error: [GHC-18872]
    • Couldn't match type ‘Many’ with ‘One’
        arising from a non-linear pattern
    • In the pattern: Solo x
      In an equation for ‘<>’: Solo x <> Solo y = Solo (x <> y)
      In the instance declaration for ‘Semigroup (Solo a)’
    |
168 |   Solo x <> Solo y = Solo (x <> y)
    |   ^^^^^^
```

**Expected behavior**

Success.

**Comment by treeowl** [comment]
That's very strange. Any idea what might have changed? `Solo x` is surely linear, no?

**Comment by Lysxia** [comment]
I think it worked with 9.6.0 alpha1, so that would narrow the possible cause. But I'm not familiar with the linear type implementation beyond that.

**Comment by treeowl** [comment]
Have you opened a GHC ticket?

**Comment by monoidal** [comment]
The `Solo` constructor has been renamed to `MkSolo` in 9.6 to avoid punning.

For backwards compatibility, there's a `Solo` pattern synonym. But pattern synonyms don't support linearity at the moment.

I'm not sure how to solve this, other than patching the code to use MkSolo.

**Comment by aspiwack** [comment]
Damn @monoidal you beat me by a few seconds! The offending commit is 2463df2fe21b5b37ecada3df8c6726c534d24590 . @tek you broke my library!

**Comment by treeowl** [comment]
@monoidal Good lort. Did they also break everything in `Data.Semigroup` and `Data.Monoid` and `Data.Functor.Compose`?

**Comment by aspiwack** [comment]
In theory I would prefer always supporting one version of GHC that is on Stackage. That being said, we can consider moving master to only supporting 9.6 and make a release for that. Otherwise we have a bit of infrastructure for version-dependent definitions. Maybe that's the best way to go, it's cheap, and conservative.

**Comment by treeowl** [comment]
@aspiwack I think it's pretty unfriendly to tie people to one compiler version, or to anything Stack related.

**Comment by monoidal** [comment]
@treeowl Pretty much every use of the `Solo` data constructor in `linear-base` breaks in 9.6, because it now refers to the non-linear pattern synonym. GHC's `base` and related modules are unaffected since they don't expose linear functions or rely on them.

Fortunately the nonpunning list/tuple proposal introduces a pattern for `MkSolo` only, so higher tuples will not be affected.

**Comment by treeowl** [comment]
@monoidal I'm just wondering about other `base` types that are traditionally punned, like `Const`, `First`, and `Compose`.

**Comment by monoidal** [comment]
Apologies, I misunderstood your question. Only `Solo` was renamed. If the other types are renamed to avoid punning, they'll also pose a problem.

I'm less worried about that though. For tuples, there was pressure to remove punning because they have special syntax (and `Solo` was done for consistency) and they are used often. For other types, the renaming is not that urgent - even if GHC gets dependent types, it'll have to support punning anyway.

**Comment by treeowl** [comment]
That's a relief. While I admit it makes sense, I've never been a big fan of the `MkName` convention. I believe I first saw it in Idris 1; do you happen to know where it came from originally, or how it reached Haskell?

**Comment by monoidal** [comment]
I don't know the original source. The first GHC commit from 1996 already defines `data TCE = MkTCE (UniqFM TyCon)`.

**Comment by Lysxia** [comment]
This seems easy to fix while remaining compatible with old GHCs.

> Otherwise we have a bit of infrastructure for version-dependent definitions.

I don't know about what infrastructure you already have, but just to give a concrete solution, I'm partial to CPP:

```
#if __GLASGOW_HASKELL__ < 906
#define MkSolo Solo
#endif
```

**Comment by aspiwack** [comment]
I try to avoid CPP pretty much like the plague. We have been using a cabal-based solution. See https://github.com/tweag/linear-base/blob/a899377327f9ade3247cab54c22b7ff7afca9f52/linear-base.cabal#L121-L125

**Comment by facundominguez** [comment]
> I try to avoid CPP pretty much like the plague.

Out of curiosity, is the rationale documented somewhere?

**Comment by monoidal** [comment]
There's a Tweag blogpost: https://www.tweag.io/blog/2019-06-27-cpp-considered-harmful/

**Comment by aspiwack** [comment]
I've made a very quick shim at #438 . I… uh… only need to test it with 9.6…
